import type { CSSProperties } from 'react'
import { theme } from '../theme/tokens'

type LandingCssProperties = CSSProperties & Record<`--${string}`, string | number>

const landing = theme.component.landing

export const landingCssVariables: LandingCssProperties = {
  '--cream': theme.color.cream,
  '--cream-dark': theme.color.creamDark,
  '--cream-mid': theme.color.creamMid,
  '--purple': theme.color.purple,
  '--purple-light': theme.color.purpleLight,
  '--purple-pale': theme.color.purplePale,
  '--purple-dark': theme.color.purpleDark,
  '--ink': theme.color.ink,
  '--ink-60': theme.color.ink60,
  '--ink-30': theme.color.ink30,
  '--ink-10': theme.color.ink10,
  '--kakao': theme.color.kakao,
  '--white': theme.color.white,
  '--serif': landing.fontFamily.serif,
  '--sans': landing.fontFamily.sans,
  '--landing-container-width': `${landing.layout.containerMaxWidth}px`,
  '--landing-container-wide-width': `${landing.layout.containerWideMaxWidth}px`,
  '--landing-section-y': `${landing.layout.sectionPaddingY}px`,
  '--landing-section-x': `${landing.layout.sectionPaddingX}px`,
  '--landing-section-mobile-y': `${landing.layout.sectionMobilePaddingY}px`,
  '--landing-section-mobile-x': `${landing.layout.sectionMobilePaddingX}px`,
  '--landing-nav-height': `${landing.navigation.height}px`,
  '--landing-nav-x': `${landing.navigation.paddingX}px`,
  '--landing-nav-mobile-x': `${landing.navigation.mobilePaddingX}px`,
  '--landing-nav-bg': landing.navigation.background,
  '--landing-nav-bg-scrolled': landing.navigation.backgroundScrolled,
  '--landing-nav-border': landing.navigation.border,
  '--landing-nav-blur': `${landing.navigation.backdropBlur}px`,
  '--landing-hero-top': `${landing.hero.paddingTop}px`,
  '--landing-hero-x': `${landing.hero.paddingX}px`,
  '--landing-hero-bottom': `${landing.hero.paddingBottom}px`,
  '--landing-hero-grid': `${landing.hero.gridSize}px`,
  '--landing-hero-grid-color': landing.hero.gridColor,
  '--landing-hero-title-wide': `${landing.hero.titleWideSize}px`,
  '--landing-hero-title-compact': `${landing.hero.titleCompactSize}px`,
  '--landing-theme-gap': `${landing.themes.trackGap}px`,
  '--landing-theme-duration': `${landing.motion.themeMarqueeDurationMs}ms`,
  '--landing-theme-card-width': `${landing.themes.cardWidth}px`,
  '--landing-theme-card-height': `${landing.themes.cardHeight}px`,
  '--landing-theme-card-radius': `${landing.themes.cardRadius}px`,
  '--landing-fade-duration': `${landing.motion.fadeUpDurationMs}ms`,
  '--landing-fade-distance': `${landing.motion.fadeUpDistance}px`,
  '--landing-footer-columns': landing.footer.columns,
  '--landing-footer-columns-tablet': landing.footer.columnsTablet,
  '--landing-footer-columns-compact': landing.footer.columnsCompact,
}
